 
name: Snyk example 
on: 
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
         SNYK_TOKEN: '26f826df-809e-40b6-8307-040f15de3b9f'

